# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: composer:latest

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
   
after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"
   
build:
  stage: build
  script:
    - composer install
    - cp .env.sample .env
   
code_sniffer:
  stage: test
  script: 
    - ./vendor/bin/phpcs ./app
   
mess_detector:
  stage: test
  script: 
    - ./vendor/bin/phpmd ./app
    
test:
  stage: test
  script: 
    - ./vendor/bin/phpunit ./tests/Unit/.
   
deploy:
  stage: deploy
  script:
    - echo "Do your deploy here"
